/**
 * @file Unit tests for generateSchemaCode.
 */
import { generateSchemaCode } from "./generate-schema-code";
import type { BetterAuthDBSchema } from "@better-auth/core/db";

describe("generateSchemaCode", () => {
	const basicTables: BetterAuthDBSchema = {
		user: {
			modelName: "user",
			fields: {
				email: { type: "string", unique: true },
				name: { type: "string" },
			},
		},
		session: {
			modelName: "session",
			fields: {
				userId: { type: "string", index: true },
				token: { type: "string", unique: true },
			},
		},
	};

	it("generates valid TypeScript code", () => {
		const code = generateSchemaCode({ tables: basicTables });

		expect(code).toContain("import { DynamoDBClient }");
		expect(code).toContain("import { applyTableSchemas }");
		expect(code).toContain("import type { TableSchema }");
		expect(code).toContain("const tableSchemas: TableSchema[]");
		expect(code).toContain("await applyTableSchemas");
	});

	it("includes header comment with file name", () => {
		const code = generateSchemaCode({
			tables: basicTables,
			file: "my-tables.ts",
		});

		expect(code).toContain("DynamoDB Table Schemas for Better Auth");
		expect(code).toContain("Generated by: npx @better-auth/cli generate");
		expect(code).toContain("npx ts-node my-tables.ts");
	});

	it("uses default file name in header when not provided", () => {
		const code = generateSchemaCode({ tables: basicTables });

		expect(code).toContain("npx ts-node dynamodb-tables.ts");
	});

	it("includes table schemas as JSON", () => {
		const code = generateSchemaCode({ tables: basicTables });

		expect(code).toContain('"tableName": "user"');
		expect(code).toContain('"tableName": "session"');
	});

	it("creates GSI for indexed fields", () => {
		const code = generateSchemaCode({ tables: basicTables });

		expect(code).toContain("user_email_idx");
		// Default composite indexes are applied, so session gets userId_createdAt and token_createdAt
		expect(code).toContain("session_userId_createdAt_idx");
		expect(code).toContain("session_token_createdAt_idx");
	});

	it("applies tableNamePrefix to table names", () => {
		const code = generateSchemaCode({
			tables: basicTables,
			tableNamePrefix: "auth_",
		});

		expect(code).toContain('"tableName": "auth_user"');
		expect(code).toContain('"tableName": "auth_session"');
	});

	it("does not prefix when tableNamePrefix is undefined", () => {
		const code = generateSchemaCode({
			tables: basicTables,
			tableNamePrefix: undefined,
		});

		expect(code).toContain('"tableName": "user"');
		expect(code).not.toContain('"tableName": "undefined');
	});

	it("respects schemaOptions for composite indexes", () => {
		const code = generateSchemaCode({
			tables: basicTables,
			schemaOptions: {
				compositeIndexes: {
					session: [{ partitionKey: "userId", sortKey: "token" }],
				},
			},
		});

		expect(code).toContain("session_userId_token_idx");
	});

	it("generates parseable JSON in output", () => {
		const code = generateSchemaCode({ tables: basicTables });

		// Extract the JSON array from the generated code
		const match = code.match(/const tableSchemas: TableSchema\[\] = (\[[\s\S]*?\]);/);
		expect(match).toBeDefined();

		if (match) {
			const jsonStr = match[1];
			expect(() => JSON.parse(jsonStr)).not.toThrow();
		}
	});

	it("includes all required table definition fields", () => {
		const code = generateSchemaCode({ tables: basicTables });

		expect(code).toContain('"attributeDefinitions"');
		expect(code).toContain('"keySchema"');
		expect(code).toContain('"billingMode": "PAY_PER_REQUEST"');
	});
});
