/**
 * @file Generate TypeScript code for DynamoDB table creation.
 *
 * This module generates executable TypeScript code that creates DynamoDB tables
 * based on Better Auth schema definitions. The generated code uses the
 * `applyTableSchemas` function from this package.
 */
import type { BetterAuthDBSchema } from "@better-auth/core/db";
import { convertToTableSchemas } from "../table-schemas/from-better-auth";
import type { GenerateTableSchemasOptions } from "../table-schemas/types";

export type GenerateSchemaCodeOptions = GenerateTableSchemasOptions & {
	/**
	 * Output file path (used in generated comments).
	 */
	file?: string;
	/**
	 * Table name prefix to apply to all table names.
	 * If provided, the generated code will prefix all table names.
	 */
	tableNamePrefix?: string;
};

/**
 * Generate TypeScript code that creates DynamoDB tables from Better Auth schema.
 *
 * The generated code is an executable TypeScript script that:
 * 1. Imports necessary dependencies
 * 2. Defines the table schemas
 * 3. Calls `applyTableSchemas` to create/update tables
 *
 * @param props.tables - Better Auth database schema
 * @param props.file - Output file path (for comments)
 * @param props.tableNamePrefix - Prefix to apply to table names
 * @returns Generated TypeScript code as a string
 */
const applyTableNamePrefix = (
	schemas: ReturnType<typeof convertToTableSchemas>,
	prefix: string | undefined,
): ReturnType<typeof convertToTableSchemas> => {
	if (!prefix) {
		return schemas;
	}
	return schemas.map((schema) => ({
		...schema,
		tableName: `${prefix}${schema.tableName}`,
	}));
};

export const generateSchemaCode = (props: {
	tables: BetterAuthDBSchema;
	file?: string;
	tableNamePrefix?: string;
	schemaOptions?: GenerateTableSchemasOptions;
}): string => {
	const tableSchemas = convertToTableSchemas(props.tables, props.schemaOptions);
	const fileName = props.file ?? "dynamodb-tables.ts";
	const finalSchemas = applyTableNamePrefix(tableSchemas, props.tableNamePrefix);
	const schemasJson = JSON.stringify(finalSchemas, null, 2);

	return `/**
 * DynamoDB Table Schemas for Better Auth
 *
 * Generated by: npx @better-auth/cli generate
 * Run this script to create/update DynamoDB tables:
 *   npx ts-node ${fileName}
 */
import { DynamoDBClient } from "@aws-sdk/client-dynamodb";
import { applyTableSchemas } from "better-auth-dynamodb";
import type { TableSchema } from "better-auth-dynamodb";

const tableSchemas: TableSchema[] = ${schemasJson};

const client = new DynamoDBClient({});

await applyTableSchemas({ client, tables: tableSchemas });
console.log("DynamoDB tables created/updated successfully.");
`;
};
