/**
 * @file DynamoDB adapter error definitions.
 */

export type DynamoDBAdapterErrorCode =
	| "MISSING_CLIENT"
	| "MISSING_TABLE_RESOLVER"
	| "MISSING_PRIMARY_KEY"
	| "MISSING_WHERE_INPUT"
	| "MISSING_QUERY_PLAN_INPUT"
	| "MISSING_JOIN_PLAN_INPUT"
	| "MISSING_STRATEGY_INPUT"
	| "MISSING_JOIN_STRATEGY_INPUT"
	| "MISSING_JOIN_EXECUTION_INPUT"
	| "MISSING_EXECUTOR_INPUT"
	| "MISSING_INDEX_RESOLVER"
	| "MISSING_KEY_CONDITION"
	| "MISSING_SCAN_LIMIT"
	| "SCAN_PAGE_LIMIT"
	| "BATCH_GET_UNPROCESSED"
	| "INVALID_BATCH_GET_ATTEMPTS"
	| "INVALID_BATCH_GET_BACKOFF"
	| "MISSING_TABLE_SCHEMA"
	| "MISSING_ATTRIBUTE_DEFINITION"
	| "ATTRIBUTE_DEFINITION_MISMATCH"
	| "TABLE_WAIT_TIMEOUT"
	| "TRANSACTION_LIMIT"
	| "UNSUPPORTED_OPERATOR"
	| "UNSUPPORTED_JOIN"
	| "UNSUPPORTED_TRANSACTION"
	| "INVALID_UPDATE";

/**
 * Adapter error with a stable error code.
 */
export class DynamoDBAdapterError extends Error {
	constructor(public code: DynamoDBAdapterErrorCode, message: string) {
		super(message);
		this.name = "DynamoDBAdapterError";
	}
}
